### ISSUE TITLE
Advanced options for the vast

### ISSUE THREAD

**Issue by supersh86** [openplayerjs/openplayerjs#7]
I had 2 ideas about VAST
1 extended download ima.js
Sometimes ima.js is blocked through dns & filters, so it would be nice to add either a url or upload via php.
url - mysite.com/ima.js
To download php, you need to disable the ima download using the script, so that the webmaster downloads the script yourself.
url - false
2 several vast streams.
Sometimes a site uses several VAST streams, in case the first one does not have a creative.
vast{
https://adsite1.com/vast.xml
https://adsite2.com/vast.xml
https://adsite3.com/vast.xml
}

**Comment by rafa8626** [comment]
What I can do is to add a new config element where you configure HLS and Dash players to include IMA, like `ima: { path: https://mysite.com/ima.js }`.

As per the various VAST streams, it's more complicated. If I understand correctly, you load one and then tests if it works; if not you would use a different one right?

**Comment by supersh86** [comment]
Yes that's right

If there is no creative, ima returns an error of 303.
After it you can refer to another thread.

**Comment by rafa8626** [comment]
That one may take more time since I'll have to refactor more of the Ads part to ensure this workflow. I can give you the URL support for IMA today, but the other part I'll have to scope it

**Comment by rafa8626** [comment]
OK download the master branch and now in your configuration file include `ads` element:
```javascript
new OpenPlayer(...., {
   ads: {
       url: '[YOUR URL]'
   }
})
```
Let me know if it works for you

**Comment by rafa8626** [comment]
This parameter may change once I implement the multiple streams so stay tuned

**Comment by rafa8626** [comment]
@supersh86 Please download the master branch and let me know if it works. So as a whole, this is how you will use all these features:
```javascript
new OpenPlayer(...., [
     'ADS_URL1',
     'ADS_URL2',
    ...
], false, {
   ads: {
       url: '[YOUR URL]'
   }
})
```

**Comment by rafa8626** [comment]
Can this issue be closed?

**Comment by supersh86** [comment]
Yes, testing vast channel of advertisers for a very long time, so for now you can close.

Thanks!

**Comment by supersh86** [comment]
I carefully tested the changes.
1 On your site in the second player can not now connect advertising.
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fsingle_ad_samples%26ciu_szs%3D300x250%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvast%26unviewed_position_start%3D1%26cust_params%3Ddeployment%253Ddevsite%2526sample_ct%253Dnonlinearvpaid2js%26correlator%3D

2 A queue error which was at a slow (3mbit) rate returned.

**Comment by rafa8626** [comment]
It should be fixed now in the main website; please confirm

**Comment by supersh86** [comment]
mm No

https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fsingle_ad_samples%26ciu_szs%3D300x250%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvast%26unviewed_position_start%3D1%26cust_params%3Ddeployment~3Ddevsite~26sample_ct~3Dlinearvpaid2js%26correlator%3D

**Comment by rafa8626** [comment]
I can see the Ad coming up
<img width="702" alt="screen shot 2018-09-15 at 12 46 49 pm" src="https://user-images.githubusercontent.com/910829/45588623-839e2080-b8e5-11e8-8283-00eb40dec758.png">

**Comment by supersh86** [comment]
I guess I have a bad cache update.
In occasion of loading of advertising on small speed the problem remained.

**Comment by supersh86** [comment]
It seems to me that there is a problem with the time of initialization of advertising.
The manifest (metadata) video is loaded earlier than the advertisement.

**Comment by supersh86** [comment]
I mean not ads, but the google ima engine itself.

**Comment by supersh86** [comment]
![Imgur](https://i.imgur.com/w9p5xBH.png)
Adsmanager is null

**Comment by rafa8626** [comment]
I think since the URL has an error it destroys the Ads player and that’s why you are seeing it as null; I’ll test this scenario but can you post the URL you were trying to see?

**Comment by supersh86** [comment]
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fsingle_ad_samples%26ciu_szs%3D300x250%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvast%26unviewed_position_start%3D1%26cust_params%3Ddeployment~3Ddevsite~26sample_ct~3Dlinearvpaid2js%26correlator%3D

**Comment by supersh86** [comment]
can you simply test the time for the initialization of all the ima components from you and how? We are with you in different parts of the world are and ping to the servers google we have different

**Comment by rafa8626** [comment]
I have tested it using low network (the one you gave me in a previous ticket) and I was able to get the Ads coming in. Let's just keep an eye on this, but so far seems to be working as expected

**Comment by supersh86** [comment]
Test more with my advertising link.
It is located in Russia.

https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fout.pladform.ru%2FgetVast%3Fpl%3D115252%26type%3Dpreroll%26license%3D1%26thematic%3D687%26age%3D4%26duration%3D1448%26target%3Dweb-html5%26mobile%26mobileapp%26adformat%3D1

**Comment by rafa8626** [comment]
@supersh86 with the URL you provided, I consistently see 2 errors coming up:
![screen shot 2018-09-21 at 1 10 22 pm](https://user-images.githubusercontent.com/910829/45895689-d6714f80-bd9f-11e8-82b9-7572adabf9ad.png)
![screen shot 2018-09-21 at 1 10 51 pm](https://user-images.githubusercontent.com/910829/45895690-d6714f80-bd9f-11e8-80e2-d9b48c942356.png)

By reading [this thread](https://groups.google.com/forum/#!topic/ima-sdk/yCztNv9x20E), only thing I can say is that is an error from the VAST source

**Comment by rafa8626** [comment]
Also, while I was testing, I realized that VAST came empty
![screen shot 2018-09-21 at 1 15 28 pm](https://user-images.githubusercontent.com/910829/45895901-7929ce00-bda0-11e8-9c01-bd7a94a92e25.png)

So I'll close the loop on this thread by indicating that this is an issue with the source itself and not with the player

**Comment by supersh86** [comment]
Hey again.
I originally wrote about the error on the example of Google ads.
Its vast I for example.

Maybe it does not work in your country. But the error appears as in Google and with this advertiser.

**Comment by supersh86** [comment]
look this video https://streamable.com/8dquj

I'm testing this url 
https://www.openplayerjs.com/embed.html?file=https%3A%2F%2Fcommondatastorage.googleapis.com%2Fgtv-videos-bucket%2Fsample%2FTearsOfSteel.mp4&type=video&ads=https%3A%2F%2Fpubads.g.doubleclick.net%2Fgampad%2Fads%3Fsz%3D640x480%26iu%3D%2F124319096%2Fexternal%2Fsingle_ad_samples%26ciu_szs%3D300x250%26impl%3Ds%26gdfp_req%3D1%26env%3Dvp%26output%3Dvast%26unviewed_position_start%3D1%26cust_params%3Ddeployment~3Ddevsite~26sample_ct~3Dlinearvpaid2js%26correlator%3D

**Comment by rafa8626** [comment]
I’ll check this definitely. But can you send me a screenshot of what you are seeing as an error so I can try to reproduce this?

**Comment by rafa8626** [comment]
Ok I saw the video and I will try to imitate it again. But just as is right now I’m able to see the video (even on my phone)
